apply plugin: 'com.android.application'

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.hasmobi.eyerest"
        minSdkVersion 19
        targetSdkVersion 34
        versionCode 3
        versionName "3.0.0"
        multiDexEnabled true
        multiDexKeepFile file('multidex-config.txt')
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.hasmobi.eyerest'
}

repositories {
    maven {
        url "https://jitpack.io"
    }
    google()
    mavenCentral()
}


dependencies {
//    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.preference:preference:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.browser:browser:1.4.0'
    implementation 'androidx.media:media:1.6.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'com.wdullaer:materialdatetimepicker:1.5.3'
    implementation 'org.adw.library:discrete-seekbar:1.0.0'
    implementation 'com.intuit.sdp:sdp-android:1.0.2'
    // Re-enabled core Firebase dependencies (app uses them)
    implementation 'com.google.firebase:firebase-analytics:21.0.0'
    implementation 'com.google.firebase:firebase-messaging:23.0.6'
    implementation 'com.google.firebase:firebase-config:21.1.0'
    // Removed deprecated dependencies: firebase-invites, firebase-crash
    implementation 'org.jdeferred.v2:jdeferred-core:2.0.0-beta2'
    implementation 'com.thebluealliance:spectrum:0.6.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "io.noties.markwon:core:4.6.2"
    // Color picker library https://github.com/the-blue-alliance/spectrum
    // http://facebook.github.io/shimmer-android/
}

apply plugin: 'com.google.gms.google-services'
